Validators justifying the epoch boundary block at the start of the current epoch
Consensys-Incorporated/teku pull request #167
Opened 2019-01-07 15:53 UTC by dangerousfood

Method implementation for [validators justifying the epoch boundary block at the start of the current epoch](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#helpers).

2019-01-07 17:14 UTC, dangerousfood commented
- [ ] get_current_epoch_boundary_attestations
- [ ] get_attestation_participants
- [ ] cell_div8

2019-01-22 15:47 UTC, jrhea requested changes
Just one request to uncomment the conditional that makes epoch processing happen every 64 slots.  That shouldn't be checked in as it is specific to your debugging and development of epoch processing.

2019-01-22 15:47 UTC, jrhea commented on ethereum/beaconchain/src/main/java/tech/pegasys/artemis/state/StateTransition.java
> +    // if (state.getSlot() % Constants.EPOCH_LENGTH == 0) {
You should leave this uncommented.  Code that other people are working on need the epoch processing to only happen every 64 slots.

2019-01-22 16:40 UTC, jrhea approved these changes
lgtm

2019-01-22 16:51 UTC, merged